-- GENERATED by scripts/demo-field-shapes.mjs — edit that, not this.
--
-- The home ranch's pastures on real survey quarters next to the fields
-- (021_boundaries.sql), and their water points inside them.

update public.pastures set legal_description = 'Home Ranch · SW-21-40-25-W4', boundary = st_multi(st_makeenvelope(-113.555423, 52.448574, -113.543690, 52.455799, 4326))
 where id = '0de30000-0000-4000-8000-000000000415';
update public.pastures set legal_description = 'Home Ranch · NW-21-40-25-W4', boundary = st_multi(st_makeenvelope(-113.555419, 52.455859, -113.543686, 52.463083, 4326))
 where id = '0de30000-0000-4000-8000-000000000416';
update public.pastures p set legal_description = 'Home Ranch · NW-15-40-25-W4', boundary = b.geom
  from public.field_boundaries b
 where p.id = '0de30000-0000-4000-8000-000000000417' and b.field_id = '0de30000-0000-4000-8000-000000000104' and b.valid_to is null;
update public.pastures set area_acres = round((st_area(boundary::geography) / 4046.86)::numeric, 1),
       boundary_analysis = st_multi(st_buffer(boundary::geography, -15)::geometry)
 where id in ('0de30000-0000-4000-8000-000000000415', '0de30000-0000-4000-8000-000000000416', '0de30000-0000-4000-8000-000000000417');

update public.cattle_water set geom = st_setsrid(st_makepoint(-113.544512, 52.454715), 4326) where name = 'Yard trough';
update public.cattle_water set geom = st_setsrid(st_makepoint(-113.550139, 52.460193), 4326) where name = 'East Bush dugout';
update public.cattle_water set geom = st_setsrid(st_makepoint(-113.526735, 52.444915), 4326) where name = 'Hay Flat slough';

update public.ranches set latitude = 52.455076, longitude = -113.543690
 where id = '0de30000-0000-4000-8000-000000000401';
