// Every water-chemistry measurement the app stores, and where each comes from
// in the two provincial programmes: Irrigation District Water Quality (canal,
// ArcGIS field names) and Alberta Environment's Long-Term River Network
// (OData variable names). No imports, so the Netlify pull and the browser
// share it. Generated from both programmes' own field lists, October 2026;
// a chemical either one starts testing for needs a line here to be kept.
//
// Units are the app's, not the source's: metals and pesticides in µg/L,
// everything else as the guideline tables state it. A source in another unit
// carries the scale that converts it (IDWQ reports metals in mg/L, the river
// network reports mercury in ng/L).

export type AnalyteGroup = 'salinity' | 'general' | 'nutrient' | 'bacteria' | 'metal' | 'pesticide'

export type Analyte = {
  key: string
  label: string
  group: AnalyteGroup
  unit: string
  /** IDWQ field name. */
  idwq?: string
  /** Multiply the IDWQ value by this to get the app's unit. */
  idwqScale?: number
  /** River-network variable names, each with its own scale where needed. */
  aepa?: { name: string; scale?: number }[]
}

export const ANALYTES: Analyte[] = [
  { key: 'so4_mg_l', label: "Sulphate", group: 'salinity', unit: 'mg/L', idwq: 'SO4', aepa: [{ name: "SULPHATE DISSOLVED" }] },
  { key: 'ec_us_cm', label: "Conductivity (EC)", group: 'salinity', unit: 'µS/cm', idwq: 'EC', aepa: [{ name: "SPECIFIC CONDUCTANCE (LAB)" }] },
  { key: 'tds_mg_l', label: "Total dissolved solids", group: 'salinity', unit: 'mg/L', idwq: 'TDS', aepa: [{ name: "TOTAL DISSOLVED SOLIDS (CALCD.)" }] },
  { key: 'sar', label: "Sodium adsorption ratio (SAR)", group: 'salinity', unit: '', idwq: 'SAR' },
  { key: 'na_mg_l', label: "Sodium", group: 'salinity', unit: 'mg/L', idwq: 'Na_Diss', aepa: [{ name: "SODIUM DISSOLVED/FILTERED" }] },
  { key: 'ca_mg_l', label: "Calcium", group: 'general', unit: 'mg/L', idwq: 'Ca_Diss', aepa: [{ name: "CALCIUM DISSOLVED/FILTERED" }] },
  { key: 'mg_mg_l', label: "Magnesium", group: 'general', unit: 'mg/L', idwq: 'Mg_Diss', aepa: [{ name: "MAGNESIUM DISSOLVED/FILTERED" }] },
  { key: 'cl_mg_l', label: "Chloride", group: 'salinity', unit: 'mg/L', idwq: 'Cl', aepa: [{ name: "CHLORIDE DISSOLVED" }] },
  { key: 'hco3_mg_l', label: "Bicarbonate", group: 'general', unit: 'mg/L', idwq: 'HCO3', aepa: [{ name: "BICARBONATE (CALCD.)" }] },
  { key: 'hardness_mg_l', label: "Hardness (as CaCO3)", group: 'general', unit: 'mg/L', idwq: 'Hard', aepa: [{ name: "HARDNESS TOTAL CACO3 (CALCD.)" }] },
  { key: 'ph', label: "pH", group: 'general', unit: 'pH', idwq: 'pH', aepa: [{ name: "PH (LAB)" }] },
  { key: 'fluoride_mg_l', label: "Fluoride", group: 'general', unit: 'mg/L', aepa: [{ name: "FLUORIDE DISSOLVED" }] },
  { key: 'no3n_mg_l', label: "Nitrate-N", group: 'nutrient', unit: 'mg/L', idwq: 'NO3_N', aepa: [{ name: "NITROGEN NITRATE" }] },
  { key: 'no2n_mg_l', label: "Nitrite-N", group: 'nutrient', unit: 'mg/L', idwq: 'NO2_N', aepa: [{ name: "NITROGEN NITRITE" }] },
  { key: 'no3no2n_mg_l', label: "Nitrate + nitrite-N", group: 'nutrient', unit: 'mg/L', idwq: 'NO3_N_NO2_N', aepa: [{ name: "NITROGEN NO3 & NO2" }] },
  { key: 'nh3n_mg_l', label: "Ammonia-N", group: 'nutrient', unit: 'mg/L', idwq: 'NH3_N', aepa: [{ name: "AMMONIA TOTAL" }] },
  { key: 'tp_mg_l', label: "Total phosphorus", group: 'nutrient', unit: 'mg/L', idwq: 'TP', aepa: [{ name: "PHOSPHORUS TOTAL (P)" }] },
  { key: 'k_mg_l', label: "Potassium", group: 'nutrient', unit: 'mg/L', idwq: 'K_Diss', aepa: [{ name: "POTASSIUM DISSOLVED/FILTERED" }] },
  { key: 'ecoli', label: "E. coli", group: 'bacteria', unit: 'per 100 mL', idwq: 'E_coli', aepa: [{ name: "ESCHERICHIA COLI" }] },
  { key: 'fecal_coliform', label: "Fecal coliforms", group: 'bacteria', unit: 'per 100 mL', aepa: [{ name: "COLIFORMS FECAL" }] },
  { key: 'm_aluminium', label: "Aluminium", group: 'metal', unit: 'µg/L', idwq: 'Al', idwqScale: 1000, aepa: [{ name: "ALUMINUM TOTAL RECOVERABLE" }] },
  { key: 'm_antimony', label: "Antimony", group: 'metal', unit: 'µg/L', idwq: 'Sb', idwqScale: 1000, aepa: [{ name: "ANTIMONY TOTAL RECOVERABLE" }] },
  { key: 'm_arsenic', label: "Arsenic", group: 'metal', unit: 'µg/L', idwq: 'As_', idwqScale: 1000, aepa: [{ name: "ARSENIC TOTAL RECOVERABLE" }] },
  { key: 'm_barium', label: "Barium", group: 'metal', unit: 'µg/L', idwq: 'Ba', idwqScale: 1000, aepa: [{ name: "BARIUM TOTAL RECOVERABLE" }] },
  { key: 'm_beryllium', label: "Beryllium", group: 'metal', unit: 'µg/L', idwq: 'Be', idwqScale: 1000, aepa: [{ name: "BERYLLIUM TOTAL RECOVERABLE" }] },
  { key: 'm_boron', label: "Boron", group: 'metal', unit: 'µg/L', idwq: 'B', idwqScale: 1000, aepa: [{ name: "BORON TOTAL RECOVERABLE" }] },
  { key: 'm_cadmium', label: "Cadmium", group: 'metal', unit: 'µg/L', idwq: 'Cd', idwqScale: 1000, aepa: [{ name: "CADMIUM TOTAL RECOVERABLE" }] },
  { key: 'm_chromium', label: "Chromium", group: 'metal', unit: 'µg/L', idwq: 'Cr', idwqScale: 1000, aepa: [{ name: "CHROMIUM TOTAL RECOVERABLE" }] },
  { key: 'm_cobalt', label: "Cobalt", group: 'metal', unit: 'µg/L', idwq: 'Co', idwqScale: 1000, aepa: [{ name: "COBALT TOTAL RECOVERABLE" }] },
  { key: 'm_copper', label: "Copper", group: 'metal', unit: 'µg/L', idwq: 'Cu', idwqScale: 1000, aepa: [{ name: "COPPER TOTAL RECOVERABLE" }] },
  { key: 'm_iron', label: "Iron", group: 'metal', unit: 'µg/L', idwq: 'Fe', idwqScale: 1000, aepa: [{ name: "IRON TOTAL RECOVERABLE" }] },
  { key: 'm_lead', label: "Lead", group: 'metal', unit: 'µg/L', idwq: 'Pb', idwqScale: 1000, aepa: [{ name: "LEAD TOTAL RECOVERABLE" }] },
  { key: 'm_lithium', label: "Lithium", group: 'metal', unit: 'µg/L', idwq: 'Li', idwqScale: 1000, aepa: [{ name: "LITHIUM TOTAL RECOVERABLE" }] },
  { key: 'm_manganese', label: "Manganese", group: 'metal', unit: 'µg/L', idwq: 'Mn', idwqScale: 1000, aepa: [{ name: "MANGANESE TOTAL RECOVERABLE" }] },
  { key: 'm_mercury', label: "Mercury", group: 'metal', unit: 'µg/L', idwq: 'Hg', idwqScale: 1000, aepa: [{ name: "MERCURY TOTAL", scale: 0.001 }] },
  { key: 'm_molybdenum', label: "Molybdenum", group: 'metal', unit: 'µg/L', idwq: 'Mo', idwqScale: 1000, aepa: [{ name: "MOLYBDENUM TOTAL RECOVERABLE" }] },
  { key: 'm_nickel', label: "Nickel", group: 'metal', unit: 'µg/L', idwq: 'Ni', idwqScale: 1000, aepa: [{ name: "NICKEL TOTAL RECOVERABLE" }] },
  { key: 'm_selenium', label: "Selenium", group: 'metal', unit: 'µg/L', idwq: 'Se', idwqScale: 1000, aepa: [{ name: "SELENIUM TOTAL RECOVERABLE" }] },
  { key: 'm_silver', label: "Silver", group: 'metal', unit: 'µg/L', idwq: 'Ag', idwqScale: 1000, aepa: [{ name: "SILVER TOTAL RECOVERABLE" }] },
  { key: 'm_strontium', label: "Strontium", group: 'metal', unit: 'µg/L', idwq: 'Sr', idwqScale: 1000, aepa: [{ name: "STRONTIUM TOTAL RECOVERABLE" }] },
  { key: 'm_thallium', label: "Thallium", group: 'metal', unit: 'µg/L', idwq: 'Tl', idwqScale: 1000, aepa: [{ name: "THALLIUM TOTAL RECOVERABLE" }] },
  { key: 'm_uranium', label: "Uranium", group: 'metal', unit: 'µg/L', idwq: 'U', idwqScale: 1000, aepa: [{ name: "URANIUM TOTAL RECOVERABLE" }] },
  { key: 'm_vanadium', label: "Vanadium", group: 'metal', unit: 'µg/L', idwq: 'V', idwqScale: 1000, aepa: [{ name: "VANADIUM TOTAL RECOVERABLE" }] },
  { key: 'm_zinc', label: "Zinc", group: 'metal', unit: 'µg/L', idwq: 'Zn', idwqScale: 1000, aepa: [{ name: "ZINC TOTAL RECOVERABLE" }] },
  { key: 'p_ampa', label: "AMPA (glyphosate breakdown product)", group: 'pesticide', unit: 'µg/L', idwq: 'AMPA' },
  { key: 'p_glufosinate', label: "Glufosinate", group: 'pesticide', unit: 'µg/L', idwq: 'Gluf' },
  { key: 'p_glyphosate', label: "Glyphosate", group: 'pesticide', unit: 'µg/L', idwq: 'Glyph' },
  { key: 'p_2_4_d', label: "2,4-D", group: 'pesticide', unit: 'µg/L', idwq: 'F2_4_D', aepa: [{ name: "2,4-DICHLOROPHENOXYACETIC ACID (2,4-D)" }] },
  { key: 'p_2_4_db', label: "2,4-DB", group: 'pesticide', unit: 'µg/L', idwq: 'F2_4_DB', aepa: [{ name: "2,4-DICHLOROPHENOXYBUTYRIC ACID (2,4-DB)" }] },
  { key: 'p_2_4_dcp', label: "2,4-DCP (2,4-D breakdown product)", group: 'pesticide', unit: 'µg/L', idwq: 'F2_4_DCP', aepa: [{ name: "2,4-DICHLOROPHENOL (2,4-DCP)" }] },
  { key: 'p_acetamiprid', label: "Acetamiprid", group: 'pesticide', unit: 'µg/L', idwq: 'Acet' },
  { key: 'p_alachlor', label: "Alachlor", group: 'pesticide', unit: 'µg/L', idwq: 'Alac' },
  { key: 'p_aldrin', label: "Aldrin", group: 'pesticide', unit: 'µg/L', idwq: 'Aldr', aepa: [{ name: "ALDRIN" }] },
  { key: 'p_allidochlor', label: "Allidochlor", group: 'pesticide', unit: 'µg/L', idwq: 'Alli' },
  { key: 'p_ametoctradin', label: "Ametoctradin", group: 'pesticide', unit: 'µg/L', idwq: 'Amet' },
  { key: 'p_atrazine', label: "Atrazine", group: 'pesticide', unit: 'µg/L', idwq: 'Atra', aepa: [{ name: "ATRAZINE" }] },
  { key: 'p_azinphos_methyl', label: "Azinphos-methyl", group: 'pesticide', unit: 'µg/L', idwq: 'Azin', aepa: [{ name: "AZINPHOS METHYL (GUTHION)" }] },
  { key: 'p_azoxystrobin', label: "Azoxystrobin", group: 'pesticide', unit: 'µg/L', idwq: 'Azos', aepa: [{ name: "AZOXYSTROBIN" }] },
  { key: 'p_benalaxyl', label: "Benalaxyl", group: 'pesticide', unit: 'µg/L', idwq: 'Bena' },
  { key: 'p_benfluralin', label: "Benfluralin", group: 'pesticide', unit: 'µg/L', idwq: 'Benf' },
  { key: 'p_bentazon', label: "Bentazon", group: 'pesticide', unit: 'µg/L', idwq: 'Bent', aepa: [{ name: "BENTAZON" }] },
  { key: 'p_benzoylprop_ethyl', label: "Benzoylprop-Ethyl", group: 'pesticide', unit: 'µg/L', idwq: 'Benz' },
  { key: 'p_bifenazate', label: "Bifenazate", group: 'pesticide', unit: 'µg/L', idwq: 'Bifz' },
  { key: 'p_bifenthrin', label: "Bifenthrin", group: 'pesticide', unit: 'µg/L', idwq: 'Bife' },
  { key: 'p_bixafen', label: "Bixafen", group: 'pesticide', unit: 'µg/L', idwq: 'Bixa' },
  { key: 'p_broflanilide', label: "Broflanilide", group: 'pesticide', unit: 'µg/L', idwq: 'Brof' },
  { key: 'p_bromacil', label: "Bromacil", group: 'pesticide', unit: 'µg/L', idwq: 'Broc', aepa: [{ name: "BROMACIL" }] },
  { key: 'p_bromophos_ethyl', label: "Bromophos-Ethyl", group: 'pesticide', unit: 'µg/L', idwq: 'Bro_E' },
  { key: 'p_bromopropylate', label: "Bromopropylate", group: 'pesticide', unit: 'µg/L', idwq: 'Brop' },
  { key: 'p_bromoxynil', label: "Bromoxynil", group: 'pesticide', unit: 'µg/L', idwq: 'Brox', aepa: [{ name: "BROMOXYNIL" }] },
  { key: 'p_boscalid', label: "Boscalid", group: 'pesticide', unit: 'µg/L', idwq: 'Bosc' },
  { key: 'p_bupirimate', label: "Bupirimate", group: 'pesticide', unit: 'µg/L', idwq: 'Bupi' },
  { key: 'p_butachlor', label: "Butachlor", group: 'pesticide', unit: 'µg/L', idwq: 'Buta' },
  { key: 'p_butralin', label: "Butralin", group: 'pesticide', unit: 'µg/L', idwq: 'Butr' },
  { key: 'p_butylate', label: "Butylate", group: 'pesticide', unit: 'µg/L', idwq: 'Buty' },
  { key: 'p_captan', label: "Captan", group: 'pesticide', unit: 'µg/L', idwq: 'Capt' },
  { key: 'p_carbaryl', label: "Carbaryl", group: 'pesticide', unit: 'µg/L', idwq: 'Carb', aepa: [{ name: "CARBARYL" }] },
  { key: 'p_carbofuran', label: "Carbofuran", group: 'pesticide', unit: 'µg/L', idwq: 'Crbf', aepa: [{ name: "CARBOFURAN" }] },
  { key: 'p_carboxin', label: "Carboxin", group: 'pesticide', unit: 'µg/L', idwq: 'Carbx', aepa: [{ name: "CARBOXIN (CARBATHIIN)" }] },
  { key: 'p_carfentrazone_ethyl', label: "Carfentrazone-ethyl", group: 'pesticide', unit: 'µg/L', idwq: 'Carf' },
  { key: 'p_chlorantraniliprole', label: "Chlorantraniliprole", group: 'pesticide', unit: 'µg/L', idwq: 'Chit' },
  { key: 'p_cis_chlordane', label: "Cis-Chlordane", group: 'pesticide', unit: 'µg/L', idwq: 'c_Chl' },
  { key: 'p_t_chlordane', label: "t-Chlordane", group: 'pesticide', unit: 'µg/L', idwq: 't_Ch' },
  { key: 'p_chlorimuron_ethyl', label: "Chlorimuron ethyl", group: 'pesticide', unit: 'µg/L', idwq: 'Chlm' },
  { key: 'p_chlormephos', label: "Chlormephos", group: 'pesticide', unit: 'µg/L', idwq: 'Chmp' },
  { key: 'p_chloroneb', label: "Chloroneb", group: 'pesticide', unit: 'µg/L', idwq: 'Chrn' },
  { key: 'p_chlorothalonil', label: "Chlorothalonil", group: 'pesticide', unit: 'µg/L', idwq: 'Chlo', aepa: [{ name: "CHLOROTHALONIL" }] },
  { key: 'p_chlorpyrifos', label: "Chlorpyrifos", group: 'pesticide', unit: 'µg/L', idwq: 'Chpy', aepa: [{ name: "CHLORPYRIFOS ETHYL" }] },
  { key: 'p_chlorpyrifos_methyl', label: "Chlorpyrifos-Methyl", group: 'pesticide', unit: 'µg/L', idwq: 'Chl_M' },
  { key: 'p_chlorthal_dimethyl', label: "Chlorthal-Dimethyl", group: 'pesticide', unit: 'µg/L', idwq: 'Chl_D' },
  { key: 'p_chlorthiamid', label: "Chlorthiamid", group: 'pesticide', unit: 'µg/L', idwq: 'Chtm' },
  { key: 'p_clethodim', label: "Clethodim", group: 'pesticide', unit: 'µg/L', idwq: 'Clet' },
  { key: 'p_clodinafop_propargyl', label: "Clodinafop-propargyl", group: 'pesticide', unit: 'µg/L', idwq: 'Clod', aepa: [{ name: "CLODINAFOP PROPARGYL" }] },
  { key: 'p_clomazone', label: "Clomazone", group: 'pesticide', unit: 'µg/L', idwq: 'Clom' },
  { key: 'p_clopyralid', label: "Clopyralid", group: 'pesticide', unit: 'µg/L', idwq: 'Clop', aepa: [{ name: "CLOPYRALID (LONTREL)" }] },
  { key: 'p_cloransulam_methyl', label: "Cloransulam methyl", group: 'pesticide', unit: 'µg/L', idwq: 'Clora' },
  { key: 'p_clothianidin', label: "Clothianidin", group: 'pesticide', unit: 'µg/L', idwq: 'Cloth', aepa: [{ name: "CLOTHIANIDIN" }] },
  { key: 'p_cyantraniliprole', label: "Cyantraniliprole", group: 'pesticide', unit: 'µg/L', idwq: 'Cyan' },
  { key: 'p_cycloate', label: "Cycloate", group: 'pesticide', unit: 'µg/L', idwq: 'Cycl' },
  { key: 'p_cyfluthrin', label: "Cyfluthrin", group: 'pesticide', unit: 'µg/L', idwq: 'Cyfl' },
  { key: 'p_cypermethrin_beta', label: "Cypermethrin-beta", group: 'pesticide', unit: 'µg/L', idwq: 'Cypb' },
  { key: 'p_cypermethrin_zeta', label: "Cypermethrin-zeta", group: 'pesticide', unit: 'µg/L', idwq: 'Cypz' },
  { key: 'p_cyhalothrin_lambda', label: "Cyhalothrin lambda", group: 'pesticide', unit: 'µg/L', idwq: 'CyhL', aepa: [{ name: "LAMBDA-CYHALOTHRIN" }] },
  { key: 'p_cyprodinil', label: "Cyprodinil", group: 'pesticide', unit: 'µg/L', idwq: 'Cypr' },
  { key: 'p_o_p_ddd', label: "o,p'-DDD", group: 'pesticide', unit: 'µg/L', idwq: 'o_p_DDD' },
  { key: 'p_p_p_ddd', label: "p,p'-DDD", group: 'pesticide', unit: 'µg/L', idwq: 'p_p_DDD' },
  { key: 'p_o_p_dde', label: "o,p'-DDE", group: 'pesticide', unit: 'µg/L', idwq: 'o_p_DDE' },
  { key: 'p_p_p_dde', label: "p,p'-DDE", group: 'pesticide', unit: 'µg/L', idwq: 'p_p_DDE' },
  { key: 'p_o_p_ddt', label: "o,p'-DDT", group: 'pesticide', unit: 'µg/L', idwq: 'o_p_DDT' },
  { key: 'p_p_p_ddt', label: "p,p'-DDT", group: 'pesticide', unit: 'µg/L', idwq: 'p_p_DDT' },
  { key: 'p_deltamethrin', label: "Deltamethrin", group: 'pesticide', unit: 'µg/L', idwq: 'Delt', aepa: [{ name: "DELTAMETHRIN" }] },
  { key: 'p_desmetryn', label: "Desmetryn", group: 'pesticide', unit: 'µg/L', idwq: 'Desm' },
  { key: 'p_diazinon', label: "Diazinon", group: 'pesticide', unit: 'µg/L', idwq: 'Diaz', aepa: [{ name: "DIAZINON" }] },
  { key: 'p_dicamba', label: "Dicamba", group: 'pesticide', unit: 'µg/L', idwq: 'Dicm', aepa: [{ name: "DICAMBA (BANVEL)" }] },
  { key: 'p_dichlobenil', label: "Dichlobenil", group: 'pesticide', unit: 'µg/L', idwq: 'Dicb' },
  { key: 'p_dichlorprop', label: "Dichlorprop (2,4-DP)", group: 'pesticide', unit: 'µg/L', idwq: 'Dcpr', aepa: [{ name: "2,4-DICHLORPROP (2,4-DP)" }] },
  { key: 'p_dichlorvos', label: "Dichlorvos", group: 'pesticide', unit: 'µg/L', idwq: 'Dicv' },
  { key: 'p_dichlofenthion', label: "Dichlofenthion", group: 'pesticide', unit: 'µg/L', idwq: 'Dicl' },
  { key: 'p_diclofop', label: "Diclofop", group: 'pesticide', unit: 'µg/L', idwq: 'Dicf', aepa: [{ name: "DICLOFOP METHYL (HOEGRASS)" }] },
  { key: 'p_dieldrin', label: "Dieldrin", group: 'pesticide', unit: 'µg/L', idwq: 'Diel', aepa: [{ name: "DIELDRIN" }] },
  { key: 'p_difenoconazole', label: "Difenoconazole", group: 'pesticide', unit: 'µg/L', idwq: 'Dife', aepa: [{ name: "DIFENOCONAZOLE" }] },
  { key: 'p_dimethachlor', label: "Dimethachlor", group: 'pesticide', unit: 'µg/L', idwq: 'Dimc' },
  { key: 'p_dimethenamid_p', label: "Dimethenamid-P", group: 'pesticide', unit: 'µg/L', idwq: 'Dimt' },
  { key: 'p_dimethoate', label: "Dimethoate", group: 'pesticide', unit: 'µg/L', idwq: 'Dime', aepa: [{ name: "DIMETHOATE (CYGON)" }] },
  { key: 'p_dimethomorph', label: "Dimethomorph", group: 'pesticide', unit: 'µg/L', idwq: 'Dimh' },
  { key: 'p_dinotefuran', label: "Dinotefuran", group: 'pesticide', unit: 'µg/L', idwq: 'Dino' },
  { key: 'p_dioxathion', label: "Dioxathion", group: 'pesticide', unit: 'µg/L', idwq: 'Diox' },
  { key: 'p_diphenamid', label: "Diphenamid", group: 'pesticide', unit: 'µg/L', idwq: 'Diph' },
  { key: 'p_diuron', label: "Diuron", group: 'pesticide', unit: 'µg/L', idwq: 'Diur', aepa: [{ name: "DIURON" }] },
  { key: 'p_alpha_endosulfan', label: "Alpha-Endosulfan", group: 'pesticide', unit: 'µg/L', idwq: 'Endo', aepa: [{ name: "ALPHA-ENDOSULFAN" }] },
  { key: 'p_endrin', label: "Endrin", group: 'pesticide', unit: 'µg/L', idwq: 'Endr' },
  { key: 'p_eptc', label: "EPTC", group: 'pesticide', unit: 'µg/L', idwq: 'EPTC', aepa: [{ name: "CARBAMATE (EPTC)" }] },
  { key: 'p_ethalfluralin', label: "Ethalfluralin", group: 'pesticide', unit: 'µg/L', idwq: 'Etfl', aepa: [{ name: "ETHALFLURALIN (EDGE)" }] },
  { key: 'p_ethion', label: "Ethion", group: 'pesticide', unit: 'µg/L', idwq: 'Ethi', aepa: [{ name: "ETHION" }] },
  { key: 'p_ethofumesate', label: "Ethofumesate", group: 'pesticide', unit: 'µg/L', idwq: 'Etho', aepa: [{ name: "ETHOFUMESATE" }] },
  { key: 'p_etradiazole', label: "Etradiazole", group: 'pesticide', unit: 'µg/L', idwq: 'Etra' },
  { key: 'p_etrimphos', label: "Etrimphos", group: 'pesticide', unit: 'µg/L', idwq: 'Etri' },
  { key: 'p_famoxadone', label: "Famoxadone", group: 'pesticide', unit: 'µg/L', idwq: 'Famx' },
  { key: 'p_fenamidone', label: "Fenamidone", group: 'pesticide', unit: 'µg/L', idwq: 'Fena' },
  { key: 'p_fenchlorphos', label: "Fenchlorphos", group: 'pesticide', unit: 'µg/L', idwq: 'Fenc' },
  { key: 'p_fenhexamid', label: "Fenhexamid", group: 'pesticide', unit: 'µg/L', idwq: 'Fenh' },
  { key: 'p_fenoxaprop', label: "Fenoxaprop", group: 'pesticide', unit: 'µg/L', idwq: 'Feno', aepa: [{ name: "FENOXAPROP-P-ETHYL" }] },
  { key: 'p_fenthion', label: "Fenthion", group: 'pesticide', unit: 'µg/L', idwq: 'Fent' },
  { key: 'p_flamoxadone', label: "Flamoxadone", group: 'pesticide', unit: 'µg/L', idwq: 'Flam' },
  { key: 'p_flamprop_isopropyl', label: "Flamprop-Isopropyl", group: 'pesticide', unit: 'µg/L', idwq: 'Fla_I' },
  { key: 'p_flamprop_methyl', label: "Flamprop-Methyl", group: 'pesticide', unit: 'µg/L', idwq: 'Fla_M' },
  { key: 'p_flonicamid', label: "Flonicamid", group: 'pesticide', unit: 'µg/L', idwq: 'Floni' },
  { key: 'p_fluazifop_p_butyl', label: "Fluazifop-p-butyl", group: 'pesticide', unit: 'µg/L', idwq: 'Flua', aepa: [{ name: "FLUAZIFOP" }] },
  { key: 'p_fludioxonil', label: "Fludioxonil", group: 'pesticide', unit: 'µg/L', idwq: 'Flud' },
  { key: 'p_flumetralin', label: "Flumetralin", group: 'pesticide', unit: 'µg/L', idwq: 'Flum' },
  { key: 'p_flumioxazin', label: "Flumioxazin", group: 'pesticide', unit: 'µg/L', idwq: 'Flux' },
  { key: 'p_flupyradifurone', label: "Flupyradifurone", group: 'pesticide', unit: 'µg/L', idwq: 'Flup' },
  { key: 'p_fluroxypyr', label: "Fluroxypyr", group: 'pesticide', unit: 'µg/L', idwq: 'Flur', aepa: [{ name: "FLUROXYPYR" }] },
  { key: 'p_flutriafol', label: "Flutriafol", group: 'pesticide', unit: 'µg/L', idwq: 'Flut' },
  { key: 'p_fluxapyroxad', label: "Fluxapyroxad", group: 'pesticide', unit: 'µg/L', idwq: 'Fluxa' },
  { key: 'p_folpet', label: "Folpet", group: 'pesticide', unit: 'µg/L', idwq: 'Folp' },
  { key: 'p_fonofos', label: "Fonofos", group: 'pesticide', unit: 'µg/L', idwq: 'Fono' },
  { key: 'p_alpha_hch', label: "Alpha-HCH", group: 'pesticide', unit: 'µg/L', idwq: 'a_HCH', aepa: [{ name: "ALPHA-BENZENEHEXACHLORIDE (BHC)" }] },
  { key: 'p_beta_hch', label: "Beta-HCH", group: 'pesticide', unit: 'µg/L', idwq: 'b_HCH' },
  { key: 'p_delta_hch', label: "Delta-HCH", group: 'pesticide', unit: 'µg/L', idwq: 'd_HCH' },
  { key: 'p_lindane', label: "Lindane", group: 'pesticide', unit: 'µg/L', idwq: 'Lind', aepa: [{ name: "GAMMA-BENZENEHEXACHLORIDE (BHC) (LINDANE)" }] },
  { key: 'p_halosulfuron_methyl', label: "Halosulfuron-methyl", group: 'pesticide', unit: 'µg/L', idwq: 'Halo' },
  { key: 'p_heptachlor', label: "Heptachlor", group: 'pesticide', unit: 'µg/L', idwq: 'Hept' },
  { key: 'p_heptachlor_epoxide', label: "Heptachlor epoxide", group: 'pesticide', unit: 'µg/L', idwq: 'HepE' },
  { key: 'p_hexazinone', label: "Hexazinone", group: 'pesticide', unit: 'µg/L', idwq: 'HexZ' },
  { key: 'p_imazamethabenz', label: "Imazamethabenz", group: 'pesticide', unit: 'µg/L', idwq: 'Imzb', aepa: [{ name: "IMAZAMETHABENZ METHYL" }] },
  { key: 'p_imazethapyr', label: "Imazethapyr", group: 'pesticide', unit: 'µg/L', idwq: 'Imaz', aepa: [{ name: "IMAZETHAPYR" }] },
  { key: 'p_imidacloprid', label: "Imidacloprid", group: 'pesticide', unit: 'µg/L', idwq: 'Imid', aepa: [{ name: "IMIDACLOPRID" }] },
  { key: 'p_ipconazole', label: "Ipconazole", group: 'pesticide', unit: 'µg/L', idwq: 'Ipco' },
  { key: 'p_iprodione', label: "Iprodione", group: 'pesticide', unit: 'µg/L', idwq: 'Ipro', aepa: [{ name: "IPRODIONE" }] },
  { key: 'p_isofenphos', label: "Isofenphos", group: 'pesticide', unit: 'µg/L', idwq: 'Isof' },
  { key: 'p_kresoxim', label: "Kresoxim", group: 'pesticide', unit: 'µg/L', idwq: 'Kres' },
  { key: 'p_linuron', label: "Linuron", group: 'pesticide', unit: 'µg/L', idwq: 'Mala', aepa: [{ name: "LINURON" }] },
  { key: 'p_malathion', label: "Malathion", group: 'pesticide', unit: 'µg/L', idwq: 'Mala2', aepa: [{ name: "MALATHION" }] },
  { key: 'p_mcpa', label: "MCPA", group: 'pesticide', unit: 'µg/L', idwq: 'MCPA', aepa: [{ name: "MCPA" }] },
  { key: 'p_mcpa_ehe', label: "MCPA-EHE", group: 'pesticide', unit: 'µg/L', idwq: 'MCPA_EHE' },
  { key: 'p_mcpb', label: "MCPB", group: 'pesticide', unit: 'µg/L', idwq: 'MCPB', aepa: [{ name: "MCPB" }] },
  { key: 'p_mecoprop', label: "Mecoprop (MCPP)", group: 'pesticide', unit: 'µg/L', idwq: 'MCPP', aepa: [{ name: "MCPP (MECOPROP)" }] },
  { key: 'p_metalaxyl', label: "Metalaxyl", group: 'pesticide', unit: 'µg/L', idwq: 'Meta', aepa: [{ name: "METALAXYL-M" }] },
  { key: 'p_metolachlor', label: "Metolachlor", group: 'pesticide', unit: 'µg/L', idwq: 'Mecz', aepa: [{ name: "METOLACHLOR" }] },
  { key: 'p_metconazole', label: "Metconazole", group: 'pesticide', unit: 'µg/L', idwq: 'Metp', aepa: [{ name: "METCONAZOLE" }] },
  { key: 'p_methoprene', label: "Methoprene", group: 'pesticide', unit: 'µg/L', idwq: 'Metc' },
  { key: 'p_methoxychlor', label: "Methoxychlor", group: 'pesticide', unit: 'µg/L', idwq: 'Meto', aepa: [{ name: "METHOXYCHLOR (P,P'-METHOXYCHLOR)" }] },
  { key: 'p_metrafenone', label: "Metrafenone", group: 'pesticide', unit: 'µg/L', idwq: 'Metf' },
  { key: 'p_metribuzin', label: "Metribuzin", group: 'pesticide', unit: 'µg/L', idwq: 'Metb', aepa: [{ name: "METRIBUZIN" }] },
  { key: 'p_mirex', label: "Mirex", group: 'pesticide', unit: 'µg/L', idwq: 'Mire' },
  { key: 'p_monolinuron', label: "Monolinuron", group: 'pesticide', unit: 'µg/L', idwq: 'MonL' },
  { key: 'p_myclobutanil', label: "Myclobutanil", group: 'pesticide', unit: 'µg/L', idwq: 'Mycb' },
  { key: 'p_naled', label: "Naled", group: 'pesticide', unit: 'µg/L', idwq: 'Nale' },
  { key: 'p_napropamide', label: "Napropamide", group: 'pesticide', unit: 'µg/L', idwq: 'Napr', aepa: [{ name: "NAPROPAMIDE" }] },
  { key: 'p_nicotine', label: "Nicotine", group: 'pesticide', unit: 'µg/L', idwq: 'Nico' },
  { key: 'p_nitenpyram', label: "Nitenpyram", group: 'pesticide', unit: 'µg/L', idwq: 'Nite' },
  { key: 'p_nitrapyrin', label: "Nitrapyrin", group: 'pesticide', unit: 'µg/L', idwq: 'Nitr' },
  { key: 'p_oxycarboxin', label: "Oxycarboxin", group: 'pesticide', unit: 'µg/L', idwq: 'Oxyc', aepa: [{ name: "OXYCARBOXIN" }] },
  { key: 'p_oxyfluorfen', label: "Oxyfluorfen", group: 'pesticide', unit: 'µg/L', idwq: 'Oxfl' },
  { key: 'p_pendimethalin', label: "Pendimethalin", group: 'pesticide', unit: 'µg/L', idwq: 'Pend' },
  { key: 'p_cis_permethrin', label: "Cis-Permethrin", group: 'pesticide', unit: 'µg/L', idwq: 'c_Per' },
  { key: 'p_trans_permethrin', label: "Trans-Permethrin", group: 'pesticide', unit: 'µg/L', idwq: 't_Per' },
  { key: 'p_phorate', label: "Phorate", group: 'pesticide', unit: 'µg/L', idwq: 'Phor', aepa: [{ name: "PHORATE (THIMET)" }] },
  { key: 'p_phosmet', label: "Phosmet", group: 'pesticide', unit: 'µg/L', idwq: 'Phos' },
  { key: 'p_picloram', label: "Picloram", group: 'pesticide', unit: 'µg/L', idwq: 'Picl', aepa: [{ name: "PICLORAM (TORDON)" }] },
  { key: 'p_picoxystrobin', label: "Picoxystrobin", group: 'pesticide', unit: 'µg/L', idwq: 'Pico', aepa: [{ name: "PICOXYSTROBIN" }] },
  { key: 'p_piperonyl_butoxide', label: "Piperonyl butoxide", group: 'pesticide', unit: 'µg/L', idwq: 'PipB' },
  { key: 'p_pirimicarb', label: "Pirimicarb", group: 'pesticide', unit: 'µg/L', idwq: 'Pica' },
  { key: 'p_pirimiphos_ethyl', label: "Pirimiphos-Ethyl", group: 'pesticide', unit: 'µg/L', idwq: 'Pir_E' },
  { key: 'p_pirimiphos_methyl', label: "Pirimiphos-Methyl", group: 'pesticide', unit: 'µg/L', idwq: 'Pir_M' },
  { key: 'p_procymidone', label: "Procymidone", group: 'pesticide', unit: 'µg/L', idwq: 'Proc_' },
  { key: 'p_prometon', label: "Prometon", group: 'pesticide', unit: 'µg/L', idwq: 'Prom' },
  { key: 'p_prometryn', label: "Prometryn", group: 'pesticide', unit: 'µg/L', idwq: 'Prty' },
  { key: 'p_propetamphos', label: "Propetamphos", group: 'pesticide', unit: 'µg/L', idwq: 'Prof' },
  { key: 'p_propham', label: "Propham", group: 'pesticide', unit: 'µg/L', idwq: 'Prop' },
  { key: 'p_propiconazole', label: "Propiconazole", group: 'pesticide', unit: 'µg/L', idwq: 'Proi', aepa: [{ name: "PROPICONAZOLE" }] },
  { key: 'p_propoxur', label: "Propoxur", group: 'pesticide', unit: 'µg/L', idwq: 'Prox' },
  { key: 'p_propoxycarbazone', label: "Propoxycarbazone", group: 'pesticide', unit: 'µg/L', idwq: 'Propo' },
  { key: 'p_propyzamide', label: "Propyzamide", group: 'pesticide', unit: 'µg/L', idwq: 'Proa' },
  { key: 'p_prothioconazole_desthio', label: "Prothioconazole-desthio", group: 'pesticide', unit: 'µg/L', idwq: 'ProD' },
  { key: 'p_pymetrozine', label: "Pymetrozine", group: 'pesticide', unit: 'µg/L', idwq: 'Pyme' },
  { key: 'p_pyraclostrobin', label: "Pyraclostrobin", group: 'pesticide', unit: 'µg/L', idwq: 'Pyra', aepa: [{ name: "PYRACLOSTROBIN" }] },
  { key: 'p_pyrasulfotole', label: "Pyrasulfotole", group: 'pesticide', unit: 'µg/L', idwq: 'Pyras' },
  { key: 'p_pyridaben', label: "Pyridaben", group: 'pesticide', unit: 'µg/L', idwq: 'Pyrd', aepa: [{ name: "PYRIDABEN" }] },
  { key: 'p_pyrimethanil', label: "Pyrimethanil", group: 'pesticide', unit: 'µg/L', idwq: 'Pyrm' },
  { key: 'p_pyroxasulfone', label: "Pyroxasulfone", group: 'pesticide', unit: 'µg/L', idwq: 'Pyro' },
  { key: 'p_quinclorac', label: "Quinclorac", group: 'pesticide', unit: 'µg/L', idwq: 'Quin', aepa: [{ name: "QUINCLORAC" }] },
  { key: 'p_quinoxyfen', label: "Quinoxyfen", group: 'pesticide', unit: 'µg/L', idwq: 'Quix' },
  { key: 'p_quintozene', label: "Quintozene", group: 'pesticide', unit: 'µg/L', idwq: 'Quit' },
  { key: 'p_quizalofop_ethyl', label: "Quizalofop-ethyl", group: 'pesticide', unit: 'µg/L', idwq: 'Quiz', aepa: [{ name: "QUIZALOFOP" }] },
  { key: 'p_saflufenacil', label: "Saflufenacil", group: 'pesticide', unit: 'µg/L', idwq: 'Safl' },
  { key: 'p_sedaxane', label: "Sedaxane", group: 'pesticide', unit: 'µg/L', idwq: 'Seda' },
  { key: 'p_simazine', label: "Simazine", group: 'pesticide', unit: 'µg/L', idwq: 'Sima', aepa: [{ name: "SIMAZINE" }] },
  { key: 'p_spirodiclofen', label: "Spirodiclofen", group: 'pesticide', unit: 'µg/L', idwq: 'Spid' },
  { key: 'p_spiromesifen', label: "Spiromesifen", group: 'pesticide', unit: 'µg/L', idwq: 'Spir' },
  { key: 'p_spiroxamine', label: "Spiroxamine", group: 'pesticide', unit: 'µg/L', idwq: 'Spix' },
  { key: 'p_sulfentrazone', label: "Sulfentrazone", group: 'pesticide', unit: 'µg/L', idwq: 'Slfz' },
  { key: 'p_sulfotep', label: "Sulfotep", group: 'pesticide', unit: 'µg/L', idwq: 'Sulf' },
  { key: 'p_sulfoxaflor', label: "Sulfoxaflor", group: 'pesticide', unit: 'µg/L', idwq: 'Sulfo' },
  { key: 'p_sulprophos', label: "Sulprophos", group: 'pesticide', unit: 'µg/L', idwq: 'Sulp' },
  { key: 'p_tebuconazole', label: "Tebuconazole", group: 'pesticide', unit: 'µg/L', idwq: 'Tebu', aepa: [{ name: "TEBUCONAZOLE" }] },
  { key: 'p_tembotrione', label: "Tembotrione", group: 'pesticide', unit: 'µg/L', idwq: 'Temb' },
  { key: 'p_terbacil', label: "Terbacil", group: 'pesticide', unit: 'µg/L', idwq: 'Tebc' },
  { key: 'p_terbufos', label: "Terbufos", group: 'pesticide', unit: 'µg/L', idwq: 'Tebf', aepa: [{ name: "TERBUFOS" }] },
  { key: 'p_terbutryn', label: "Terbutryn", group: 'pesticide', unit: 'µg/L', idwq: 'Tebt' },
  { key: 'p_tetraconazole', label: "Tetraconazole", group: 'pesticide', unit: 'µg/L', idwq: 'Tetr' },
  { key: 'p_tetradifon', label: "Tetradifon", group: 'pesticide', unit: 'µg/L', idwq: 'Tefo' },
  { key: 'p_tetramethrin', label: "Tetramethrin", group: 'pesticide', unit: 'µg/L', idwq: 'Tetm' },
  { key: 'p_tetrasul', label: "Tetrasul", group: 'pesticide', unit: 'µg/L', idwq: 'Tesu' },
  { key: 'p_thiacloprid', label: "Thiacloprid", group: 'pesticide', unit: 'µg/L', idwq: 'Thiac' },
  { key: 'p_triallate', label: "Triallate", group: 'pesticide', unit: 'µg/L', idwq: 'Tral', aepa: [{ name: "TRIALLATE (AVADEX BW)" }] },
  { key: 'p_thiamethoxam', label: "Thiamethoxam", group: 'pesticide', unit: 'µg/L', idwq: 'Thiam', aepa: [{ name: "THIAMETHOXAM" }] },
  { key: 'p_triclopyr', label: "Triclopyr", group: 'pesticide', unit: 'µg/L', idwq: 'Tric', aepa: [{ name: "TRICLOPYR" }] },
  { key: 'p_thifensulfuron_methyl', label: "Thifensulfuron-methyl", group: 'pesticide', unit: 'µg/L', idwq: 'Trife' },
  { key: 'p_trifloxystrobin', label: "Trifloxystrobin", group: 'pesticide', unit: 'µg/L', idwq: 'Trif', aepa: [{ name: "TRIFLOXYSTROBIN" }] },
  { key: 'p_trifluralin', label: "Trifluralin", group: 'pesticide', unit: 'µg/L', idwq: 'Trfl', aepa: [{ name: "TRIFLURALIN (TREFLAN)" }] },
  { key: 'p_thiophanate_methyl', label: "Thiophanate-methyl", group: 'pesticide', unit: 'µg/L', idwq: 'Thio' },
  { key: 'p_triticonazole', label: "Triticonazole", group: 'pesticide', unit: 'µg/L', idwq: 'Trit', aepa: [{ name: "TRITICONAZOLE" }] },
  { key: 'p_vinclozolin', label: "Vinclozolin", group: 'pesticide', unit: 'µg/L', idwq: 'Vinc', aepa: [{ name: "VINCLOZOLIN" }] },
  { key: 'p_zoxamide', label: "Zoxamide", group: 'pesticide', unit: 'µg/L', idwq: 'Zoxm' },
  { key: 'p_4_chloro_2_methylphenol', label: "4-Chloro-2-Methylphenol", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "4-CHLORO-2-METHYLPHENOL" }] },
  { key: 'p_aldicarb', label: "Aldicarb", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "ALDICARB" }] },
  { key: 'p_aldicarb_sulfone', label: "Aldicarb Sulfone", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "ALDICARB SULFONE" }] },
  { key: 'p_aldicarb_sulfoxide', label: "Aldicarb Sulfoxide", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "ALDICARB SULFOXIDE" }] },
  { key: 'p_aminocarb', label: "Aminocarb", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "AMINOCARB" }] },
  { key: 'p_aminopyralid', label: "Aminopyralid", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "AMINOPYRALID" }] },
  { key: 'p_atrazine_desethyl', label: "Atrazine Desethyl", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "ATRAZINE DESETHYL" }] },
  { key: 'p_atrazine_desisopropyl', label: "Atrazine Desisopropyl", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "ATRAZINE DESISOPROPYL" }] },
  { key: 'p_benomyl', label: "Benomyl", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "BENOMYL" }] },
  { key: 'p_clodinafop_acid_metabolite', label: "Clodinafop Acid Metabolite", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "CLODINAFOP ACID METABOLITE" }] },
  { key: 'p_cyanazine', label: "Cyanazine", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "CYANAZINE" }] },
  { key: 'p_disulfoton', label: "Disulfoton", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "DISULFOTON (DI-SYSTON)" }] },
  { key: 'p_hexaconazole', label: "Hexaconazole", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "HEXACONAZOLE" }] },
  { key: 'p_imazamox', label: "Imazamox", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "IMAZAMOX" }] },
  { key: 'p_methomyl', label: "Methomyl", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "METHOMYL" }] },
  { key: 'p_monuron', label: "Monuron", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "MONURON" }] },
  { key: 'p_oh_carbofuran', label: "Oh-Carbofuran", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "OH-CARBOFURAN" }] },
  { key: 'p_parathion', label: "Parathion", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "PARATHION" }] },
  { key: 'p_permethrin', label: "Permethrin", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "PERMETHRIN" }] },
  { key: 'p_prothioconazole', label: "Prothioconazole", group: 'pesticide', unit: 'µg/L', aepa: [{ name: "PROTHIOCONAZOLE" }] },
]

export const ANALYTE_BY_KEY = new Map(ANALYTES.map((a) => [a.key, a]))
export const ANALYTE_BY_IDWQ = new Map(ANALYTES.filter((a) => a.idwq).map((a) => [a.idwq!, a]))
export const ANALYTE_BY_AEPA = new Map(
  ANALYTES.flatMap((a) => (a.aepa ?? []).map((v) => [v.name, { analyte: a, scale: v.scale ?? 1 }] as const)),
)
