/** Every in-page tab, for the app search. Generated by reading each page; keep in step when a tab is added. */
export type TabEntry = {
  label: string
  page: string
  to: string
  exact: boolean
  keywords?: string
  /** Shown only to managers / admins, as the tab itself is. */
  managerOnly?: boolean
  adminOnly?: boolean
}

/*
 * How each page reads its tab (so a `to` here actually lands on it):
 * - useTab (src/lib/useTab.ts): `?tab=<key>` — Harvest, Calculator, Checklists, Chemicals, Combine,
 *   Contracts, Markets, Hauling, Map, Meeting, Plan, Utilities, Fertilizer.
 * - QuickBooks: `?tab=<key>` read directly.
 * - Fertilizer: `?tab=<view key>` (the second row); a group name (`?tab=Prices`) opens that group's
 *   last-used view.
 * - Irrigation (AIMM, /irrigation): `?view=overview|detail|setup`.
 * - Irrigation info (/irrigation-info): `?tab=pump` (anything else is Pivot Information).
 * - Settings: `?tab=<name>` (case-insensitive); `?section=` opens a part of My Account;
 *   Farm setup's parts are `?part=`.
 * - Tasks/Checklists and Calendar/Monthly are routes under SubTabLayout.
 * Spaces in tab keys are left unencoded, the way src/lib/tiles.ts writes them.
 */
export const TAB_ENTRIES: TabEntry[] = [
  // Tasks / Checklists (SubTabLayout in App.tsx — each tab is its own route)
  { label: 'Tasks', page: 'Tasks', to: '/tasks', exact: true, keywords: 'to-do list jobs' },
  { label: 'Checklists', page: 'Tasks', to: '/checklists', exact: true },

  // Calendar / Monthly (SubTabLayout in App.tsx)
  { label: 'Calendar', page: 'Calendar', to: '/calendar', exact: true },
  { label: 'Monthly', page: 'Calendar', to: '/monthly', exact: true, keywords: 'monthly plan' },

  // Checklists page (useTab 'checklists')
  { label: 'Runs', page: 'Checklists', to: '/checklists?tab=runs', exact: true, keywords: 'this year checklist runs' },
  { label: 'Templates', page: 'Checklists', to: '/checklists?tab=templates', exact: true, keywords: 'checklist templates' },

  // Monday meeting (useTab 'meeting')
  { label: 'Agenda', page: 'Monday meeting', to: '/meeting?tab=agenda', exact: true },
  { label: 'This week', page: 'Monday meeting', to: '/meeting?tab=calendar', exact: true, keywords: 'week calendar' },
  { label: "What's new", page: 'Monday meeting', to: '/meeting?tab=whats-new', exact: true, keywords: 'changes updates app changelog' },

  // Map section (useTab 'map')
  { label: 'Map', page: 'Map', to: '/map?tab=map', exact: true, keywords: 'farm map' },
  { label: 'Topography', page: 'Map', to: '/map?tab=topography', exact: true, keywords: 'elevation contours' },
  { label: 'Profit / Loss', page: 'Map', to: '/map?tab=profit', exact: true, keywords: 'profit loss map net per acre' },

  // Weather (local state, remembered in localStorage — not in the URL)
  { label: 'Next 24 hours', page: 'Weather', to: '/weather', exact: false, keywords: 'hourly today forecast' },
  { label: 'Week', page: 'Weather', to: '/weather', exact: false, keywords: 'weekly forecast' },

  // Crop financials (/plan, useTab 'planner')
  { label: 'Plan', page: 'Crop financials', to: '/plan?tab=plan', exact: true, keywords: 'crop plan' },
  { label: 'Budget', page: 'Crop financials', to: '/plan?tab=budget', exact: true },
  { label: 'Breakeven', page: 'Crop financials', to: '/plan?tab=breakeven', exact: true, keywords: 'break even' },
  { label: 'Actuals', page: 'Crop financials', to: '/plan?tab=actuals', exact: true, keywords: 'actual costs' },
  { label: 'Field work', page: 'Crop financials', to: '/plan?tab=field work', exact: true },
  { label: 'Farm costs', page: 'Crop financials', to: '/plan?tab=farm costs', exact: true, keywords: 'fixed costs overhead' },

  // Markets (/markets, useTab 'markets')
  { label: 'Prices', page: 'Markets', to: '/markets?tab=prices', exact: true, keywords: 'crop prices' },
  { label: 'Basis', page: 'Markets', to: '/markets?tab=basis', exact: true },
  { label: 'Targets', page: 'Markets', to: '/markets?tab=targets', exact: true, keywords: 'price targets' },

  // Contracts (useTab 'contracts')
  { label: 'Contracts', page: 'Contracts', to: '/contracts?tab=contracts', exact: true },
  { label: 'Scale tickets', page: 'Contracts', to: '/contracts?tab=tickets', exact: true, keywords: 'tickets weigh' },
  { label: 'Position', page: 'Contracts', to: '/contracts?tab=position', exact: true, keywords: 'deliveries sold' },
  { label: 'Cash flow', page: 'Contracts', to: '/contracts?tab=cashflow', exact: true },

  // Harvest (useTab 'harvest'; the bins tabs are BinsPage embedded)
  { label: 'Bins', page: 'Harvest', to: '/harvest?tab=bins', exact: true, keywords: 'storage bins allocations inventory' },
  { label: 'Bin estimator', page: 'Harvest', to: '/harvest?tab=estimator', exact: true, keywords: 'storage estimator' },
  { label: 'Bin map', page: 'Harvest', to: '/harvest?tab=map', exact: true, keywords: 'storage yard map' },
  { label: 'Moisture', page: 'Harvest', to: '/harvest?tab=moisture', exact: true, keywords: 'moisture tester 919 safe ranges harvest readiness' },

  // Combine (useTab 'combine'; "From the manual" only on a CR-series combine)
  { label: 'Starting settings', page: 'Combine', to: '/combine?tab=setup', exact: true, keywords: 'combine settings setup' },
  { label: 'What do I change?', page: 'Combine', to: '/combine?tab=fix', exact: true, keywords: 'troubleshoot adjust' },
  { label: 'Loss check', page: 'Combine', to: '/combine?tab=loss', exact: true, keywords: 'combine loss' },
  { label: 'From the manual', page: 'Combine', to: '/combine?tab=book', exact: true, keywords: 'operator manual CR' },

  // Calculator (useTab 'calculator')
  { label: 'Water', page: 'Calculator', to: '/calculator?tab=water', exact: true, keywords: 'volume flow depth' },
  { label: 'Bushels & weight', page: 'Calculator', to: '/calculator?tab=bushels', exact: true, keywords: 'bushel calculator' },
  { label: 'General', page: 'Calculator', to: '/calculator?tab=general', exact: true, keywords: 'weight area distance liquid unit converter' },
  { label: 'Planter', page: 'Calculator', to: '/calculator?tab=planter', exact: true, keywords: 'seeding rate' },

  // Chemicals (useTab 'chemicals')
  { label: 'Registry', page: 'Chemicals', to: '/chemicals?tab=registry', exact: true, keywords: 'labels pesticide registry' },
  { label: 'Inventory', page: 'Chemicals', to: '/chemicals?tab=inventory', exact: true, keywords: 'chemical inventory shed' },
  { label: 'Prices', page: 'Chemicals', to: '/chemicals?tab=prices', exact: true, keywords: 'chemical prices pricing' },
  { label: 'Recently sprayed', page: 'Chemicals', to: '/chemicals?tab=reentry', exact: true, keywords: 're-entry reentry' },
  { label: 'Before spraying', page: 'Chemicals', to: '/chemicals?tab=spraycheck', exact: true, keywords: 'spray check label rotation' },

  // Fertilizer — group row (a group name opens that group's last-used view)
  { label: 'Soil', page: 'Fertilizer', to: '/fertilizer?tab=Soil', exact: true },
  { label: 'Plan', page: 'Fertilizer', to: '/fertilizer?tab=Plan', exact: true, keywords: 'fertilizer plan' },
  { label: 'Prices', page: 'Fertilizer', to: '/fertilizer?tab=Prices', exact: true, keywords: 'fertilizer prices' },
  // Fertilizer — views (`?tab=` takes the view key)
  { label: 'Soil tests', page: 'Fertilizer', to: '/fertilizer?tab=Soil Sampling', exact: true, keywords: 'soil sampling' },
  { label: 'Sampling map', page: 'Fertilizer', to: '/fertilizer?tab=Sampling Map', exact: true, keywords: 'soil sample sites' },
  { label: 'Nutrient history', page: 'Fertilizer', to: '/fertilizer?tab=Nutrient History', exact: true },
  { label: 'Tissue tests', page: 'Fertilizer', to: '/fertilizer?tab=Tissue Tests', exact: true },
  { label: 'Requirements', page: 'Fertilizer', to: '/fertilizer?tab=Requirements', exact: true, keywords: 'fertilizer needed' },
  { label: 'Productivity zones', page: 'Fertilizer', to: '/fertilizer?tab=Productivity Zones', exact: true, keywords: 'yield zones' },
  { label: 'Prescriptions', page: 'Fertilizer', to: '/fertilizer?tab=Prescriptions', exact: true, keywords: 'rx variable rate' },
  { label: 'Blends', page: 'Fertilizer', to: '/fertilizer?tab=Blends', exact: true, keywords: 'blend calculator' },
  { label: 'Pricing', page: 'Fertilizer', to: '/fertilizer?tab=Pricing', exact: true, keywords: 'fertilizer price book' },
  { label: 'Market', page: 'Fertilizer', to: '/fertilizer?tab=Market', exact: true, keywords: 'fertilizer market prices' },
  { label: 'ICI', page: 'Fertilizer', to: '/fertilizer?tab=ICI', exact: true, keywords: 'retailer invoices' },
  { label: 'Manure', page: 'Fertilizer', to: '/fertilizer?tab=Manure', exact: true },
  { label: 'Savings', page: 'Fertilizer', to: '/fertilizer?tab=Savings', exact: true, keywords: 'fertilizer savings' },

  // Travel & trucking (/hauling, useTab 'hauling')
  { label: 'Distances', page: 'Travel & trucking', to: '/hauling?tab=distances', exact: true, keywords: 'hauling road' },
  { label: 'Trucking', page: 'Travel & trucking', to: '/hauling?tab=trucking', exact: true, keywords: 'hauling' },
  { label: 'Fuel', page: 'Travel & trucking', to: '/hauling?tab=fuel', exact: true, keywords: 'diesel' },
  { label: 'Spreading cost', page: 'Travel & trucking', to: '/hauling?tab=spreading', exact: true },
  { label: 'Silage haul', page: 'Travel & trucking', to: '/hauling?tab=silage', exact: true },

  // Irrigation — AIMM (/irrigation reads `?view=`)
  { label: 'Overview', page: 'Irrigation', to: '/irrigation?view=overview', exact: true, keywords: 'AIMM soil moisture' },
  { label: 'Detailed View', page: 'Irrigation', to: '/irrigation?view=detail', exact: true, keywords: 'AIMM graph records' },
  { label: 'Setup', page: 'Irrigation', to: '/irrigation?view=setup', exact: true, keywords: 'AIMM setup' },
  // Irrigation — General info (/irrigation-info reads `?tab=pump`)
  { label: 'Pivot Information', page: 'Irrigation info', to: '/irrigation-info', exact: true, keywords: 'pivots' },
  { label: 'Pump Information', page: 'Irrigation info', to: '/irrigation-info?tab=pump', exact: true, keywords: 'pumps' },
  // Irrigation — River (local state; one tab per ranch plus the gauge map)
  { label: 'Home Ranch', page: 'River', to: '/river', exact: false, keywords: 'river levels' },
  { label: 'East Ranch', page: 'River', to: '/river', exact: false, keywords: 'river levels' },
  { label: 'Map', page: 'River', to: '/river', exact: false, keywords: 'river gauge map' },
  // Irrigation — Turbine control (local state)
  { label: 'Station', page: 'Turbines', to: '/turbines', exact: false, keywords: 'turbine pump station' },
  { label: 'Alarms', page: 'Turbines', to: '/turbines', exact: false, keywords: 'turbine alarms' },
  { label: 'History', page: 'Turbines', to: '/turbines', exact: false, keywords: 'turbine history' },
  { label: 'Settings', page: 'Turbines', to: '/turbines', exact: false, keywords: 'turbine settings PID' },

  // Utilities (useTab 'utilities'; Solar only when the solar feature is on)
  { label: 'Solar', page: 'Utilities', to: '/utilities?tab=solar', exact: true, keywords: 'solar panels' },
  { label: 'Power', page: 'Utilities', to: '/utilities?tab=power', exact: true, keywords: 'electricity meters' },

  // QuickBooks (`?tab=` read directly)
  { label: 'Transactions', page: 'QuickBooks', to: '/quickbooks?tab=transactions', exact: true, keywords: 'bills invoices' },
  { label: 'Spending', page: 'QuickBooks', to: '/quickbooks?tab=spending', exact: true },
  { label: 'Cash flow', page: 'QuickBooks', to: '/quickbooks?tab=cash', exact: true, keywords: 'cash flow forecast bank balance low point' },
  { label: 'Inputs vs Deere', page: 'QuickBooks', to: '/quickbooks?tab=inputs', exact: true, keywords: 'input costs fertilizer chemical seed fuel books deere per field invoices' },
  { label: 'Ask', page: 'QuickBooks', to: '/quickbooks?tab=ask', exact: true, keywords: 'ask quickbooks' },

  // Settings (`?tab=`, case-insensitive)
  { label: 'My Account', page: 'Settings', to: '/settings?tab=My Account', exact: true },
  { label: 'Users', page: 'Settings', to: '/settings?tab=Users', exact: true, managerOnly: true },
  { label: 'Access', page: 'Settings', to: '/settings?tab=Access', exact: true, adminOnly: true, keywords: 'permissions' },
  { label: 'Integrations', page: 'Settings', to: '/settings?tab=Integrations', exact: true, managerOnly: true, keywords: 'connections john deere fieldnet' },
  { label: 'Farm setup', page: 'Settings', to: '/settings?tab=Farm setup', exact: true, adminOnly: true },
  // Settings › My Account sections (`?section=` opens My Account on that section)
  { label: 'Profile', page: 'Settings', to: '/settings?section=profile', exact: true },
  { label: 'Sign-in security', page: 'Settings', to: '/settings?section=security', exact: true, keywords: 'mfa authenticator' },
  { label: 'Notifications', page: 'Settings', to: '/settings?section=notifications', exact: true, keywords: 'push alerts' },
  { label: 'Home screen', page: 'Settings', to: '/settings?section=home', exact: true, keywords: 'tiles' },
  { label: 'This device', page: 'Settings', to: '/settings?section=device', exact: true },
  // Settings › Farm setup parts (`?part=`)
  { label: 'Overview', page: 'Farm setup', to: '/settings?tab=Farm setup&part=overview', exact: true, adminOnly: true },
  { label: 'Your farm', page: 'Farm setup', to: '/settings?tab=Farm setup&part=farm', exact: true, adminOnly: true },
  { label: 'Parts of the app', page: 'Farm setup', to: '/settings?tab=Farm setup&part=features', exact: true, adminOnly: true, keywords: 'features switches' },
  { label: 'Connections', page: 'Farm setup', to: '/settings?tab=Farm setup&part=connections', exact: true, adminOnly: true, keywords: 'keys' },
  { label: 'Fitting it to your farm', page: 'Farm setup', to: '/settings?tab=Farm setup&part=customize', exact: true, adminOnly: true, keywords: 'customize' },
]
